name: dmpo
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.8
  - pytorch=2.1.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - pip
  - pip:
      - lightning==2.0.9
      - tensorboard
      - ghalton
      - tqdm
      - meshcat
      - rowan
      - numpy-quaternion
      - pyyaml