# simulation parameters
sim_dt: 0.02
sim_tf: 4.
traj: 'zig-zag-yaw'
Vwind: 0 # velocity of wind in world frame, 0 means not considering wind
initial_state: [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.01, 0.]
min_dt: 0.6 # 0.6
max_dt: 1.5 # 1.5

mass: 0.04
J: [16.571710, 16.655602, 29.261652]
a_min: [0, 0, 0, 0] # bounds of sampling action: [thrust, omega (unit: rad/s)]
a_max: [12, 12, 12, 12]
noise_process_std: [0.3, 2]

# MPPI parameters
sim_dt_MPPI: 0.02
lam: 0.003 # temparature
H: 40 # horizon
N: 8192 # number of samples
sample_std: [0.25, 0.1, 2., 0.02] # standard deviation for sampling: [thrust (unit: hovering thrust), omega (unit: rad/s)]
gamma_mean: 0.9 # learning rate
gamma_Sigma: 0. # learning rate
omega_gain: 40. # gain of the low-level controller
discount: 0.99 # discount factor in MPPI

# reward functions
alpha_p: 0.05
alpha_z: 0.0
alpha_w: 0.0
alpha_a: 0.0
alpha_R: 0.05
alpha_v: 0.0
alpha_yaw: 0.0
alpha_pitch: 0.0
alpha_u_delta: 0.0
alpha_u_thrust: 0.01
alpha_u_omega: 0.01